ant_badge_shelf:
    pattern: /shelf
    defaults: { _controller: AntBadgeBundle:Badge:shelf }
ant_badge_view:
    pattern: /{badgeId}/view
    defaults: { _controller: AntBadgeBundle:Badge:badge }
ant_badge_new:
    pattern: /new
    defaults: { _controller: AntBadgeBundle:Badge:newBadge }
ant_badge_delete:
    pattern: /{badgeId}/delete
    defaults: { _controller: AntBadgeBundle:Badge:delete }
    requirements:
        _method: DELETE
        id: "\d+"
ant_badge_edit:
    pattern: /{id}/edit
    defaults: { _controller: AntBadgeBundle:Badge:editBadge }
    #Group
ant_group_new:
    pattern: /new/group
    defaults: { _controller: AntBadgeBundle:Group:newGroup }
ant_group_delete:
    pattern: /group/{groupId}/delete
    defaults: { _controller: AntBadgeBundle:Group:delete }
    requirements:
        _method: DELETE
        id: "\d+"
ant_group_edit:
    pattern: /group/{id}/edit
    defaults: { _controller: AntBadgeBundle:Group:edit }
ant_group_view:
    pattern: /group/{groupId}/view
    defaults: { _controller: AntBadgeBundle:Group:group }
ant_group_shelf:
    pattern: /group/shelf
    defaults: { _controller: AntBadgeBundle:Group:shelf }
    #Rank
ant_rank_my_shelf:
    pattern: /rank/shelf
    defaults: { _controller: AntBadgeBundle:Rank:myShelf }
ant_rank_shelf:
    pattern: /rank/shelf/{acquired}
    defaults: { _controller: AntBadgeBundle:Rank:shelf }
ant_rank_view:
    pattern: /rank/{rankId}
    defaults: { _controller: AntBadgeBundle:Rank:rank }