badge_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BadgeBundle:Default:index }

ant_badge_view:
    pattern: /badge/{badgeId}
    defaults: { _controller: BadgeBundle:Badge:badge }
ant_badge_new:
    pattern: /badge-new
    defaults: { _controller: AntBadgeBundle:Badge:newBadge }